

services:
  web:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: matcha_web
    user: "${UID}:${GID}"
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
      - mailhog
    env_file:
      - .env
    networks:
      - matcha_network
    environment:
      - UID=${UID}
      - GID=${GID}

  db:
    image: postgres:14
    container_name: matcha_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    env_file:
      - .env
    networks:
      - matcha_network



  pgadmin:
    image: dpage/pgadmin4
    container_name: matcha_pgadmin
    ports:
      - "8888:80"
    env_file:
      - .env
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - matcha_network



  mailhog:
    image: mailhog/mailhog
    container_name: matcha_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - matcha_network



volumes:
  db_data:
  pgadmin_data:

networks:
  matcha_network:
    driver: bridge